[project]
name = "companylogogenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.6.0",
    "diffusers==0.33.1",
    "ipywidgets==8.1.7",
    "jupyter==1.1.1",
    "transformers==4.51.3",
]
